package com.comtrade.domen;

public enum ConstantBLC {

    LOGGING,USER_RETURN_DATA, USER_DATA_ENTRY, USER_DATA_UPDATE, USER_REMOVE, USER_RETURN_ID, USER_RETURN_NAME,


    THEATER_RETURN_DATA, THEATER_DATA_ENTRY, THEATER_DATA_UPDATE, THEATER_RETURN_NAME, THEATER_RETURN_ID, THEATER_REMOVE, THEATER_RETURN_NAMES,


    SHOW_RETURN_DATA, SHOW_DATA_ENTRY, SHOW_REMOVE, SHOW_NAMES_UPDATE, SHOW_UPDATE, SHOW_RETURN_ID, SHOW_RETURN_NAMES,SHOW_ID_RETURN, SHOW_NAMES,


    TERM_DATA_RETURN, TERM_DATA_ENTRY, TERM_UPDATE, TERM_REMOVE, TERM_RETURN_ID, TERM_RETURN_TIME, TERM_RETURN_TERM,



    RESERVATION_NO_TICKETS, RESERVATION_ENTRY, RESERVATION_RETURN,


    DATA_RETURN_FRONT_PAGE,

    ACTOR_RETURN_DATA, ACTOR_RETURN_SHOW, ACTOR_SAVE, ACTOR_RETURN_ID, ACTOR_SHOW_SAVE, ACTOR_REMOVE

   }
